/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package music_app;

// import org.junit.jupiter.api.Test;
// import java.io.IOException;
// import static org.junit.jupiter.api.Assertions.*;

// public class SpotifyListeningHistoryTest {

//     @Test
//     public void testGetAccessToken() {
//         String accessToken = SpotifyListeningHistory.getAccessToken("e4d903fc1791486793761f84836dd578", "921b4efe0de24566a0376a714cd8cfa9");
//         assertNotNull(accessToken);
//         assertFalse(accessToken.isEmpty());
//     }

//     @Test
//     public void testGetListeningHistory() {
//         String accessToken = SpotifyListeningHistory.getAccessToken("e4d903fc1791486793761f84836dd578", "921b4efe0de24566a0376a714cd8cfa9");
//         String listeningHistory = SpotifyListeningHistory.getListeningHistory(accessToken);
//         assertNotNull(listeningHistory);
//         assertFalse(listeningHistory.isEmpty());
//     }

//     @Test
//     public void testDumpToFile() throws IOException {
//         // Mock listening history data
//         String listeningHistory = "{\"items\": [{\"track\": {\"name\": \"Song Name\", \"artist\": \"Artist Name\"}}]}";
//         SpotifyListeningHistory.dumpToFile(listeningHistory, "test.json");

//         // Verify file was created
//         java.io.File file = new java.io.File("test.json");
//         assertTrue(file.exists());

//         // Verify file content
//         java.util.Scanner scanner = new java.util.Scanner(file);
//         StringBuilder fileContent = new StringBuilder();
//         while (scanner.hasNextLine()) {
//             fileContent.append(scanner.nextLine());
//         }
//         scanner.close();
//         assertTrue(fileContent.toString().contains("Song Name"));
//         assertTrue(fileContent.toString().contains("Artist Name"));

//         // Delete the test file
//         file.delete();
//     }
// }